spring:
  application:
    name:
      reactive-practice

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
#    initialize: true
#  sql:
#    init:
#      mode: always
#      platform: h2
#      schema-locations: classpath:schema.sql

h2:
  console:
    port: 8090

logging:
  level:
    org.springframework:
      r2dbc: debug
